# 1. Load the Dataset

Instead of using scikit-learn’s built-in datasets, load it directly from the given URL:

data_url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/housing.data"

## 👉 Hints:

Use pandas to read it.

This dataset has no headers, so you need to assign column names.

Column names can be found here: Boston Housing Attributes.

Example: ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']

In [32]:
import pandas as pd
import numpy as np

data_url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/housing.data"
column_names = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV']

df = pd.read_csv(
    data_url,
    sep = r'\s+',
    header=None,
    names=column_names
)

df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

# 2. Split the Dataset

Separate features (X) and target (y = MEDV).

Use train_test_split to split into train (80%) and test (20%).

In [33]:
from sklearn.model_selection import train_test_split

X = df.drop('MEDV', axis=1)
y = df['MEDV']

print(f"Shape of X as feature: {X.shape}")
print(f"Shape of y as target: {y.shape}")

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size = 0.2,
    random_state = 42
)

print("="*50)

print(f"Shape of X_train: {X_train.shape}")
print(f"Shape of X_test: {X_test.shape}")

print("="*50)

print(f"Shape of y_train: {y_train.shape}")
print(f"Shape of y_test: {y_test.shape}")

Shape of X as feature: (506, 13)
Shape of y as target: (506,)
==================================================
Shape of X_train: (404, 13)
Shape of X_test: (102, 13)
==================================================
Shape of y_train: (404,)
Shape of y_test: (102,)

# 3. Train Models

Import regression models:

LinearRegression

Ridge

Lasso

## 👉 Hints:

from sklearn.linear_model import LinearRegression, Ridge, Lasso

Fit each model on the training data.

In [34]:
from sklearn.linear_model import LinearRegression, Ridge, Lasso

linear_model = LinearRegression()

ridge_model = Ridge()

lesso_model = Lasso()

linear_model.fit(X_train, y_train)

ridge_model.fit(X_train, y_train)

lesso_model.fit(X_train, y_train)

Lasso()

# 4. Evaluate Models

Predict on the test set.

Calculate metrics:

Mean Squared Error (MSE)

Root Mean Squared Error (RMSE)

R² Score

Mean Absolute Error (MAE)

##👉 Hints:

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

Remember:

rmse = np.sqrt(mse)

In [35]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

linear_model_pred = linear_model.predict(X_test)
ridge_model_pred = ridge_model.predict(X_test)
lasso_model_pred = lesso_model.predict(X_test)

linear_model_mse = mean_squared_error(y_test, linear_model_pred)
ridge_model_mse = mean_squared_error(y_test, ridge_model_pred)
lasso_model_mse = mean_squared_error(y_test, lasso_model_pred)

linear_model_rmse = np.sqrt(linear_model_mse)
ridge_model_rmse = np.sqrt(ridge_model_mse)
lasso_model_rmse = np.sqrt(lasso_model_mse)

linear_model_r2 = r2_score(y_test, linear_model_pred)
ridge_model_r2 = r2_score(y_test, ridge_model_pred)
lasso_model_r2 = r2_score(y_test, lasso_model_pred)

linear_model_mae = mean_absolute_error(y_test, linear_model_pred)
ridge_model_mae = mean_absolute_error(y_test, ridge_model_pred)
lasso_model_mae = mean_absolute_error(y_test, lasso_model_pred)

print("Linear Regression  Metrics:")
print(f"MSE: {linear_model_mse}")
print(f"RMSE: {linear_model_rmse}")
print(f"R²: {linear_model_r2}")
print(f"MAE: {linear_model_mae}")

print("="*50)
print("Ridge Regression Metrics:")
print(f"MSE: {ridge_model_mse}")
print(f"RMSE: {ridge_model_rmse}")
print(f"R²: {ridge_model_r2}")
print(f"MAE: {ridge_model_mae}")

print("="*50)
print("Lasso Regression Metrics:")
print(f"MSE: {lesso_model_mse}")
print(f"RMSE: {lesso_model_rmse}")
print(f"R²: {lesso_model_r2}")
print(f"MAE: {lesso_model_mae}")

Linear Regression  Metrics:
MSE: 24.291119474973478
RMSE: 4.928602182665332
R²: 0.6687594935356326
MAE: 3.189091965887837
==================================================
Ridge Regression Metrics:
MSE: 24.477191227708644
RMSE: 4.94744289787246
R²: 0.6662221670168523
MAE: 3.1329474278055343
==================================================
Lasso Regression Metrics:
MSE: 24.409489761299707
RMSE: 4.940596093721861
R²: 0.6671453631686304
MAE: 3.2535397673681614

# 5. Compare Results

Make a comparison table:

Model

MSE

RMSE

R²

MAE

Linear Regression

...

...

...

...

Ridge Regression

...

...

...

...

Lasso Regression

...

...

...

...

In [36]:
results = pd.DataFrame({
    'Model': ['Linear Regression', 'Ridge Regression', 'Lasso Regression'],
    'MSE': [linear_model_mse, ridge_model_mse, lasso_model_mse],
    "RMSE": [linear_model_rmse, ridge_model_rmse, lasso_model_rmse],
    "R²": [linear_model_r2, ridge_model_r2, lasso_model_r2],
    "MAE": [linear_model_mae, ridge_model_mae, lasso_model_mae]
})

results.head()

               Model        MSE      RMSE        R²       MAE
0  Linear Regression  24.291119  4.928602  0.668759  3.189092
1   Ridge Regression  24.477191  4.947443  0.666222  3.132947
2   Lasso Regression  24.409490  4.940596  0.667145  3.253540